# Use the official Node.js image from the Docker Hub
FROM node:14

# Create and set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock-json.5 ./


# Copy the rest of the application code
COPY . .

# Connect to Azure Blob Storage
ENV AZURE_STORAGE_CONNECTION_STRING=$connectionString


# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["node", "app.js"]
