name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Build project
        run: npm run build
        working-directory: ./src

      - name: Test project
        run: npm test
        working-directory: ./src

      - name: Scan
        run: echo "Perform security scan"

      - name: Deploy
        run: echo "Deploy the application"
